language: node_js

node_js: stable

before_install:
- export TZ='Asia/Shanghai'

install:
- npm install -g gitbook
- npm install -g gitbook-cli
- gitbook install

script:
- gitbook build

after_success:
- git config --global user.name "Tony Deng"
- git config --global user.email "wolf.deng@gmail.com"
- git checkout -b gh-pages
- git pull origin gh-pages --rebase
- cp -R _book/* .
- git clean -fx node_modules
- git clean -fx _book
- git add .
- git commit -a -m "rebuild pages"
- git remote add upstream "https://$GH_TOKEN@github.com/tonydeng/user-stories-applied.git"
- git push upstream gh-pages

env:
  global:
    - secure: EcEfk3nQmsoqz5V0U5TLc1K7xZrYGHodularifADjK17d7I3TUKqMPs14r/Ny8fI0MS7kWPM0AzGo35IoOUuEAsTCMLjzG50dIM5I8UL6J84sM0Gq6SDhNTBMqqXtPDFUxXLedsX7W/zkAI/5g5do5h4LmvnnAMA5apPH/OcRQM=
